//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBitacorasCientificas.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoBitacorasCientificas.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administracion.
        /// </summary>
        public static string Administracion {
            get {
                return ResourceManager.GetString("Administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitacoras.
        /// </summary>
        public static string Bitacoras {
            get {
                return ResourceManager.GetString("Bitacoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitacoras Cientificas.
        /// </summary>
        public static string BitacorasCientificas {
            get {
                return ResourceManager.GetString("BitacorasCientificas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutivos.
        /// </summary>
        public static string Consecutivos {
            get {
                return ResourceManager.GetString("Consecutivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultas.
        /// </summary>
        public static string Consultas {
            get {
                return ResourceManager.GetString("Consultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Usuario.
        /// </summary>
        public static string CrearUsuario {
            get {
                return ResourceManager.GetString("CrearUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargas.
        /// </summary>
        public static string Descargas {
            get {
                return ResourceManager.GetString("Descargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores.
        /// </summary>
        public static string Errores {
            get {
                return ResourceManager.GetString("Errores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenguaje.
        /// </summary>
        public static string Lenguaje {
            get {
                return ResourceManager.GetString("Lenguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyectos.
        /// </summary>
        public static string Proyectos {
            get {
                return ResourceManager.GetString("Proyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puestos/Roles Laboratorio.
        /// </summary>
        public static string PuestosRoles {
            get {
                return ResourceManager.GetString("PuestosRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramas Cientificas.
        /// </summary>
        public static string RamasCientificas {
            get {
                return ResourceManager.GetString("RamasCientificas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Roles Laboratorio.
        /// </summary>
        public static string RolesLaboratorio {
            get {
                return ResourceManager.GetString("RolesLaboratorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Roles Usuario.
        /// </summary>
        public static string RolesUsuario {
            get {
                return ResourceManager.GetString("RolesUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguridad.
        /// </summary>
        public static string Seguridad {
            get {
                return ResourceManager.GetString("Seguridad", resourceCulture);
            }
        }
    }
}
